Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "standalone01"
    config.vm.network "private_network", ip: "192.168.50.100"
    config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
    end
  end
