---
# Source: argo-cd/templates/redis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-argocd-redis
  labels:
    helm.sh/chart: argo-cd-3.6.11
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/instance: RELEASE-NAME
