$installk3smaster = <<SCRIPT
export K3S_DATASTORE_ENDPOINT='mysql://username:password@tcp(192.168.50.14:3306)/Solutions'
sudo curl -sfL https://get.k3s.io | sh -s - server --node-taint CriticalAddonsOnly=true:NoExecute --tls-san 192.168.50.10 --node-external-ip 192.168.50.10 --node-ip 192.168.50.10
sleep 120
sudo k3s kubectl get node
sudo cat /var/lib/rancher/k3s/server/node-token
SCRIPT
Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "main01"
    config.vm.network "private_network", ip: "192.168.50.10"
    config.vm.provision "shell", inline: $installk3smaster
    config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    end
  end