---
# Source: argo-cd/templates/argocd-configs/argocd-tls-certs-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: argo-cd-3.6.11
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
  name: argocd-tls-certs-cm
