
apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: app01-deployment
  namespace: app01
spec:
  selector:
    matchLabels:
      app: app01
  replicas: 4 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
      - name: nginx
        image: image
        ports:
        - containerPort: 80
