apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: app01
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx
  selector:
    app: app01 