---
# Source: argo-cd/templates/argocd-application-controller/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: argocd-application-controller
  labels:
    helm.sh/chart: argo-cd-3.6.11
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
