apiVersion: v1
kind: Service
metadata:
  name: app02-svc
  namespace: app02
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx
  selector:
    app: app02 